# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Political Economy of Media
description: MIT 2100
baseurl: "/MIT-2100" # the subpath of your site, e.g. /blog
url: "https://brettpetch.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: MIT-2100 # the GitHub repo name for your project
github_username: brettpetch

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: brettjpetch

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: red

# Build settings
markdown: kramdown

owl: https://owl.uwo.ca/portal/site/63de366f-b9e9-42a0-a406-39fc5c2c7c23

google_analytics: UA-45906012-10

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category_index"